server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: spocbt
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  mvc:
    view:
      suffix: .html

  # ???
  datasource:
    #url: jdbc:mysql://spocbt.cafe24.com:3306/spocbt
    url: jdbc:mysql://localhost:3306/spocbt
    username: spocbt
    password: spocbm007512!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spocbt.spocbt.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    #org.mybatis: DEBUG
    #org.mybatis.spring: DEBUG
    #org.mybatis.spring.SqlSessionUtils: WARN
    jdbc.sqlonly: ERROR
    org.apache.ibatis: ERROR
    org.mybatis: ERROR
    java.sql: ERROR
    root: ERROR # 전체 애플리케이션의 기본 로그 레벨을 ERROR로 설정
    org.springframework: ERROR # Spring Framework의 ERROR 로그만 출력
    com.spocbt: ERROR # 애플리케이션 패키지에서 ERROR 로그만 출력
    org.hibernate: ERROR # Hibernate 관련 ERROR 로그만 출력
  file:
    name: app-error.log # 에러 로그 파일 이름
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 콘솔 출력 패턴
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 파일 출력 패턴

hash:
  access_secret: adsfagsdreaasdvcaasdftgsdaasdfgas
  refresh_secret: klcxjpioasnasdfkiohagirnweasdfgasd
  default_secret: asdfhpovsjknjkqw

# account
kakao:
  nativeAppKey: 8f8a62a7f1569022af5cdfbd220acf00
  restApiKey: 568e633d45565d3d7bc2f1b8b6eb098c
  javaScriptKey: ea59a2e466087091141d5d08d22d7dbd
  adminKey: 45dabb1273a0e8c4babf91da42d9f7a7
  clientSecret: UPvGkX4xriJl13Wu5lFfwiMHYVxDb1K3
  redirectUri: http://spocbt.cafe24.com/member/kakao/callback
  #redirectUri: http://172.30.1.69:8080/member/kakao/callback
  codeUrl: https://kauth.kakao.com/oauth/authorize
  tokenUrl: https://kauth.kakao.com/oauth/token
  userInfoUrl: https://kapi.kakao.com/v2/user/me

naver:
  clientId: FndeshkAJslRNhjMR6fn
  clientSecret: TEEc_iojL_
  #redirectUri: http://172.30.1.69:8080/member/naver/callback
  redirectUri: http://spocbt.cafe24.com/member/naver/callback
  codeUrl: https://nid.naver.com/oauth2.0/authorize
  tokenUrl: https://nid.naver.com/oauth2.0/token
  userInfoUrl: https://openapi.naver.com/v1/nid/me

google:
  clientId: 823999673142-jr0jdt44ctrn1lkkk34rd6dpq2cfbt4r.apps.googleusercontent.com
  clientSecret: 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
  redirectUri: http://localhost:8080/members/google/callback
  codeUrl: https://accounts.google.com/o/oauth2/v2/auth
  tokenUrl: https://oauth2.googleapis.com/token
  userInfoUrl: https://openidconnect.googleapis.com/v1/userinfo



# ???? ?? url
agreementUrl:
  kakao: ???? ?? url
  naver: ???? ?? url
  apple: ???? ?? url
  google: ???? ?? url


